name: Deploy react app with github actions
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run UTs
        run: npm test

      - name: Build production app
        run: npm run build
